package org.example.conference.shared.api;

/** Stable machine-readable API error codes. */
public enum ErrorCode {
  VALIDATION_FAILED,
  MALFORMED_REQUEST,
  CAPTCHA_INVALID,
  OPTION_INVALID,
  CONSENT_REQUIRED,
  CONSENT_INVALID,
  REQUEST_ID_CONFLICT,
  PAYLOAD_TOO_LARGE,
  RATE_LIMITED,
  STORAGE_UNAVAILABLE,
  NOT_FOUND,
  METHOD_NOT_ALLOWED,
  UNSUPPORTED_MEDIA_TYPE,
  INTERNAL_ERROR
}
