import { chromium } from '@playwright/test';
const out = process.argv[2];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 900, height: 1100 } });
const stamp = Date.now();
await page.goto('http://localhost:8088/');
await page.screenshot({ path: `${out}/01-external-form.png`, fullPage: true });
await page.getByLabel('First name').fill(' Špela ');
await page.getByLabel('Last name').fill('Screenshot');
await page.getByLabel('Email').fill(`spela.shot.${stamp}@example.org`);
await page.getByLabel('Organization / institution').fill('Inštitut');
await page.getByLabel('Workshop: Data science in practice').check();
await page.getByLabel('I am not a robot (local test captcha)').check();
await page.getByRole('button', { name: 'Submit registration' }).click();
await page.getByRole('status').waitFor();
await page.screenshot({ path: `${out}/02-external-confirmation.png`, fullPage: true });
await page.goto('http://localhost:8088/#student');
await page.reload();
await page.getByRole('button', { name: 'Submit registration' }).click();
await page.screenshot({ path: `${out}/03-student-validation.png`, fullPage: true });
await page.getByLabel('First name').fill('Luka');
await page.getByLabel('Last name').fill('Screenshot');
await page.getByLabel('Email').fill(`luka.shot.${stamp}@example.org`);
await page.getByLabel('Study institution').fill('Univerza');
await page.getByLabel('Study programme').fill('Računalništvo');
await page.getByLabel('Student ID').fill('SHOT-1');
await page.getByLabel('I am not a robot (local test captcha)').check();
await page.getByRole('button', { name: 'Submit registration' }).click();
await page.getByRole('status').waitFor();
await page.screenshot({ path: `${out}/04-student-confirmation.png`, fullPage: true });
await page.goto('http://localhost:8025/');
await page.waitForTimeout(8000);
await page.reload();
await page.screenshot({ path: `${out}/05-mailpit-inbox.png`, fullPage: true });
await browser.close();
